Ft user profile
decagonhq/decapay-mobile pull request #56
Opened 2022-09-23 20:34 UTC by omudavid

Updated UI Form Errors

2022-09-26 09:25 UTC, Osehi reviewed
Hello David,
Please, note that "Budget Description" is not a required field.
It is nullable.
Hence, no need for the error flag -
<img width="303" alt="Screenshot 2022-09-26 at 09 22 40" src="https://user-images.githubusercontent.com/40719260/192230312-e09265d7-9c77-4faa-a0b2-46d136e898f0.png">
 "Budget description is required".

2022-09-26 09:25 UTC, Osehi commented on app/src/main/java/com/decagonhq/decapay/feature/createbudget/presentation/CreateBudgetFragment.kt
> +            binding.createBudgetFragmentDescriptionTil.error = "Budget description is required"
Hello David,
Please, note that "Budget Description" is not a required field.
It is nullable.
Hence, no need for the error flag -
<img width="303" alt="Screenshot 2022-09-26 at 09 22 40" src="https://user-images.githubusercontent.com/40719260/192230312-e09265d7-9c77-4faa-a0b2-46d136e898f0.png">
 "Budget description is required".

2022-09-26 11:03 UTC, Osehi approved these changes
Good

2022-09-26 12:18 UTC, olalekan-oloba requested changes

2022-09-26 12:18 UTC, olalekan-oloba commented on app/src/main/java/com/decagonhq/decapay/feature/logexpense/presentation/LogExpenseBottomSheetFragment.kt
> +
violate DRY. this is repetition

2022-09-26 12:18 UTC, olalekan-oloba commented on app/src/main/java/com/decagonhq/decapay/feature/editlogexpense/presentation/EditLogExpenseBottomSheetFragment.kt
> +
violate DRY principle

2022-09-26 12:19 UTC, olalekan-oloba commented on app/src/main/java/com/decagonhq/decapay/feature/createbudget/presentation/CreateBudgetFragment.kt
> +            binding.createBudgetFragmentDescriptionTil.error = "Budget description is required"
Budget description is not required

2022-09-27 11:56 UTC, olalekan-oloba approved these changes

2022-09-27 12:02 UTC, merged